#!/bin/bash
# Generate small per-group driver files for both read/write tests:
#
#   wr_rd_field_test_group<N>.c  -- field API (wr_rd_field_test.c)
#   wr_rd_test_group<N>.c        -- struct API (wr_rd_test.c)
#
# Each driver #includes its test file with exactly one TEST_GROUP_N
# enabled, so each group's register region can be compiled/run in
# isolation. The test files have no main(); the driver provides it and
# calls the run_* function. The include resolves via the -I "$API_DIR"
# that the run_groups*.sh scripts pass.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(dirname "$SCRIPT_DIR")/api"

status=0

emit_drivers() {
  local src="$1" func="$2" prefix="$3" note="$4"

  if [[ ! -f "$src" ]]; then
    echo "SKIP $prefix drivers: missing $src" >&2
    return 1
  fi
  if ! grep -q "$func" "$src"; then
    echo "SKIP $prefix drivers: $src still has the old standalone-main" >&2
    echo "format; regenerate it with genapi.py first." >&2
    return 1
  fi

  local i out
  for i in $(seq 0 19); do
    out="$SCRIPT_DIR/${prefix}_group${i}.c"
    cat > "$out" <<EOF
// Auto-generated by generate_groups.sh -- driver that runs only
// TEST_GROUP_${i} of $(basename "$src") (${note}).
#define WR_RD_TEST_CUSTOM_GROUPS
#define TEST_GROUP_${i}
// For per-register checksum bisection, uncomment:
#define TRACE_WR_CHECKSUM
#define TRACE_RD_CHECKSUM
#include "$(basename "$src")"

int main(void) {
  return ${func}();
}
EOF
    echo "wrote $out (TEST_GROUP_${i} active)"
  done
}

emit_drivers "$API_DIR/wr_rd_field_test.c" run_wr_rd_field_test \
             wr_rd_field_test "field API" || status=1
emit_drivers "$API_DIR/wr_rd_test.c" run_wr_rd_test \
             wr_rd_test "struct API" || status=1

exit $status
