// Auto-generated by generate_groups.sh -- driver that runs only
// TEST_GROUP_2 of wr_rd_field_test.c (field API).
#define WR_RD_TEST_CUSTOM_GROUPS
#define TEST_GROUP_2
// For per-register checksum bisection, uncomment:
//#define TRACE_WR_CHECKSUM
//#define TRACE_RD_CHECKSUM
#include "wr_rd_field_test.c"

int main(void) {
  return run_wr_rd_field_test();
}
