#!/usr/bin/env -S sbcl --script
(require :asdf)
(let ((ql-setup (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file ql-setup) (load ql-setup)))
(let ((script-directory (make-pathname :directory (pathname-directory *load-truename*))))
  (pushnew script-directory asdf:*central-registry* :test #'equal))
(handler-case
  (let ((*standard-output* *error-output*))
    (asdf:load-system :literisc :verbose nil))
  (error (e)
         (format *error-output* "Error loading literisc: ~a~%" e)
         (sb-ext:exit :code 1)))
(in-package :lr-disasm)
(loop for line = (read-line *standard-input* nil nil)
      while line
      do (let* ((trimmed  (string-trim " " line))
                (val      (parse-integer trimmed :radix 16))
                (valid    (ldb (byte 1 68) val))
                (pc       (ldb (byte 16 52) val))
                (len      (ldb (byte 4 48) val))
                (b0       (ldb (byte 8 40) val))
                (b1       (ldb (byte 8 32) val))
                (b2       (ldb (byte 8 24) val))
                (b3       (ldb (byte 8 16) val))
                (b4       (ldb (byte 8  8) val))
                (b5       (ldb (byte 8  0) val))
                (all-bytes   (list b0 b1 b2 b3 b4 b5))
                (instr-bytes (nthcdr (- 6 len) all-bytes)))
           (format *error-output* "val=~x valid=~a pc=~x len=~a bytes=~a instr=~a~%"
                   val valid pc len all-bytes instr-bytes)
           (if (= valid 1)
               (handler-case
                 (destructuring-bind (str nr-bytes)
                   (disassemble-instr instr-bytes)
                   (declare (ignore nr-bytes))
                   (format t "~a~%" str))
                 (error (e)
                        (declare (ignore e))
                        (format t "?~%")))
               (format t " ~%"))
           (force-output)))
